# Generated by Django 5.2 on 2025-06-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_user_email_alter_user_role_alter_user_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'superadmin'), ('admin', 'admin'), ('user', 'user')], default='user', max_length=10),
        ),
    ]
