# Generated by Django 5.2 on 2025-06-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='practice_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('user', 'User')], default='user', max_length=10),
        ),
    ]
